[build]
    command = "gatsby build"
    publish = "public"

[build.environment]
    NODE_VERSION = "18.13.0"

[dev]
    command = "gatsby develop"
    targetPort=8888

#[[redirects]] 
    from = ""
    to = ""

[[plugins]]
    package = "@netlify/plugin-gatsby"